from algorithms.rsa import codegen as cg


STATE_FULL = {
    "p": 61, "q": 53, "n": 3233, "phi": 3120, "e": 17, "d": 2753,
    "m": 65, "c": pow(65, 17, 3233), "m_decrypted": 65,
}


def test_pick_pq_line():
    assert cg.pick_pq(STATE_FULL) == "p, q = 61, 53"


def test_compute_n_line():
    assert cg.compute_n(STATE_FULL) == "n = p * q  # n = 3233"


def test_compute_phi_line():
    assert cg.compute_phi(STATE_FULL) == "phi = (p - 1) * (q - 1)  # phi = 3120"


def test_pick_e_line():
    assert cg.pick_e(STATE_FULL) == "e = 17  # gcd(e, phi) == 1"


def test_compute_d_line():
    assert cg.compute_d(STATE_FULL) == "d = pow(e, -1, phi)  # d = 2753"


def test_pick_message_line():
    assert cg.pick_message(STATE_FULL) == "m = 65"


def test_encrypt_line():
    expected_c = pow(65, 17, 3233)
    assert cg.encrypt(STATE_FULL) == f"c = pow(m, e, n)  # c = {expected_c}"


def test_decrypt_line():
    assert cg.decrypt(STATE_FULL) == "m_decrypted = pow(c, d, n)  # m_decrypted = 65"


def test_info_returns_empty_string():
    assert cg.info(STATE_FULL) == ""


def test_full_script():
    script = cg.full_script(STATE_FULL)
    assert script.startswith("# RSA lesson — generated by cloak.moosha.org\n")
    assert "p, q = 61, 53" in script
    assert "m_decrypted = pow(c, d, n)" in script
    assert script.endswith("\n")
