# Generated by Django 5.1.15 on 2026-05-22 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('family', models.CharField(choices=[('asymmetric', 'Asymmetric'), ('symmetric', 'Symmetric'), ('pq', 'Post-Quantum')], max_length=20)),
                ('intro_template', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('live', 'Live'), ('coming-soon', 'Coming soon')], default='coming-soon', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('order', models.IntegerField(default=0)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.algorithm')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('slug', models.SlugField()),
                ('kind', models.CharField(choices=[('info', 'Info'), ('input-numeric', 'Numeric input'), ('input-multi', 'Multi-numeric input'), ('choose-from-list', 'Choose from list')], max_length=20)),
                ('prompt_template', models.TextField()),
                ('validator_key', models.CharField(blank=True, default='', max_length=80)),
                ('codegen_key', models.CharField(blank=True, default='', max_length=80)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step_order', models.IntegerField(default=1)),
                ('state', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('algorithm', 'slug'), name='unique_lesson_slug_per_algo'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('lesson', 'slug'), name='unique_step_slug_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_step_order_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_progress_per_user_lesson'),
        ),
    ]
