# Generated by Django 5.1.15 on 2026-05-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='help_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
