# Generated by Django 5.1.15 on 2026-05-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_step_help_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="kind",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("input-numeric", "Numeric input"),
                    ("input-multi", "Multi-numeric input"),
                    ("input-text", "Text input"),
                    ("choose-from-list", "Choose from list"),
                ],
                max_length=20,
            ),
        ),
    ]
