# Generated by Django 5.1.15 on 2026-05-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_step_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogress",
            options={
                "verbose_name": "user progress",
                "verbose_name_plural": "user progress",
            },
        ),
    ]
