# Generated by Django 5.1.15 on 2026-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_userprogress_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="family",
            field=models.CharField(
                choices=[
                    ("asymmetric", "Asymmetric"),
                    ("symmetric", "Symmetric"),
                    ("pq", "Post-Quantum"),
                    ("hsm", "HSM"),
                ],
                max_length=20,
            ),
        ),
    ]
