# Generated by Django 5.1.15 on 2026-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_algorithm_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="family",
            field=models.CharField(
                choices=[
                    ("asymmetric", "Asymmetric"),
                    ("symmetric", "Symmetric"),
                    ("hash", "Hash & MAC"),
                    ("pq", "Post-Quantum"),
                    ("hsm", "HSM"),
                    ("historical", "Historical / Pre-modern"),
                ],
                max_length=20,
            ),
        ),
    ]
