def pick_pq(state):
    return f"p, q = {state['p']}, {state['q']}"


def compute_n(state):
    return f"n = p * q  # n = {state['n']}"


def compute_phi(state):
    return f"phi = (p - 1) * (q - 1)  # phi = {state['phi']}"


def pick_e(state):
    return f"e = {state['e']}  # gcd(e, phi) == 1"


def compute_d(state):
    return f"d = pow(e, -1, phi)  # d = {state['d']}"


def pick_message(state):
    return f"m = {state['m']}"


def encrypt(state):
    return f"c = pow(m, e, n)  # c = {state['c']}"


def decrypt(state):
    return f"m_decrypted = pow(c, d, n)  # m_decrypted = {state['m_decrypted']}"


def info(_state):
    return ""


def encode_sentence(state):
    return f"encrypted = [pow(ord(ch), {state['e2']}, {state['n2']}) for ch in sentence]"


_ORDER = [pick_pq, compute_n, compute_phi, pick_e, compute_d, pick_message, encrypt, decrypt]


def full_script(state):
    import json

    lines = ["# RSA lesson — generated by cloak.moosha.org", ""]
    for fn in _ORDER:
        keys_needed = {
            pick_pq: ["p", "q"],
            compute_n: ["n"],
            compute_phi: ["phi"],
            pick_e: ["e"],
            compute_d: ["d"],
            pick_message: ["m"],
            encrypt: ["c"],
            decrypt: ["m_decrypted"],
        }[fn]
        if all(k in state for k in keys_needed):
            lines.append(fn(state))
    if state.get("sentence") is not None and state.get("e2") is not None:
        lines.append("")
        lines.append("# --- Encrypt a real sentence ---")
        lines.append(f"p2, q2 = {state['p2']}, {state['q2']}")
        lines.append(f"n2 = {state['n2']}")
        lines.append(f"phi2 = (p2 - 1) * (q2 - 1)  # {state['phi2']}")
        lines.append(f"e2 = {state['e2']}")
        lines.append(f"d2 = {state['d2']}  # modinv(e2, phi2)")
        lines.append(f"sentence = {json.dumps(state['sentence'])}")
        lines.append("encrypted = [pow(ord(ch), e2, n2) for ch in sentence]")
        lines.append('decrypted = "".join(chr(pow(c, d2, n2)) for c in encrypted)')
        lines.append("assert decrypted == sentence")
    return "\n".join(lines) + "\n"
