def pick_pq(state):
    return f"p, q = {state['p']}, {state['q']}"


def compute_n(state):
    return f"n = p * q  # n = {state['n']}"


def compute_phi(state):
    return f"phi = (p - 1) * (q - 1)  # phi = {state['phi']}"


def pick_e(state):
    return f"e = {state['e']}  # gcd(e, phi) == 1"


def compute_d(state):
    return f"d = pow(e, -1, phi)  # d = {state['d']}"


def pick_message(state):
    return f"m = {state['m']}"


def encrypt(state):
    return f"c = pow(m, e, n)  # c = {state['c']}"


def decrypt(state):
    return f"m_decrypted = pow(c, d, n)  # m_decrypted = {state['m_decrypted']}"


def info(_state):
    return ""


_ORDER = [pick_pq, compute_n, compute_phi, pick_e, compute_d, pick_message, encrypt, decrypt]


def full_script(state):
    lines = ["# RSA lesson — generated by cloak.moosha.org", ""]
    for fn in _ORDER:
        keys_needed = {
            pick_pq: ["p", "q"],
            compute_n: ["n"],
            compute_phi: ["phi"],
            pick_e: ["e"],
            compute_d: ["d"],
            pick_message: ["m"],
            encrypt: ["c"],
            decrypt: ["m_decrypted"],
        }[fn]
        if all(k in state for k in keys_needed):
            lines.append(fn(state))
    return "\n".join(lines) + "\n"
